name: 50/50photography
favicon: null
layout_spectrum: 0.25351
typography_spectrum: 0.11122
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edf7ff'
    - '#400f15'
    - '#cb8862'
    - '#41719a'
    - '#167d2b'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
