name: 5050photography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.0972
title: 5050photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#65574a'
    - '#a2a3b5'
    - '#d2d1d7'
    - '#070000'
    - '#242b4c'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
