name: 50/50photography
favicon: null
layout_spectrum: 0.25351
typography_spectrum: 0.11122
title: 5050photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8f2ff'
    - '#adbfd7'
    - '#004f89'
    - '#667f9d'
    - '#001025'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
