name: 5050photography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52405
title: 5050photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#787878'
    - '#444444'
    - '#adadad'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
