name: 5050photography
favicon: null
layout_spectrum: 0.25351
typography_spectrum: 0.11122
title: 5050photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#616161'
    - '#2d2d2d'
    - '#b8b8b8'
    - '#e7e7e7'
  brandStrength: 0.25
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
